// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Real Firebase project configuration for Pocket Organizer
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDF2qmArnB5c98Pmif0PTLkXVxN68Zcj4s',
    appId: '1:323532342809:web:b22734374293f7e4ab8c88',
    messagingSenderId: '323532342809',
    projectId: 'pocket-organizer-b01f8',
    authDomain: 'pocket-organizer-b01f8.firebaseapp.com',
    storageBucket: 'pocket-organizer-b01f8.firebasestorage.app',
    measurementId: 'G-50PEGFDN6L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1J95q5U3svN4f2WnofsECbwmBwRyqBU4',
    appId: '1:323532342809:android:976bdac9a4dd4301ab8c88',
    messagingSenderId: '323532342809',
    projectId: 'pocket-organizer-b01f8',
    storageBucket: 'pocket-organizer-b01f8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDF2qmArnB5c98Pmif0PTLkXVxN68Zcj4s',
    appId: '1:323532342809:ios:abcdef123456',
    messagingSenderId: '323532342809',
    projectId: 'pocket-organizer-b01f8',
    storageBucket: 'pocket-organizer-b01f8.firebasestorage.app',
    iosBundleId: 'com.ahad.pocketorganizer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDF2qmArnB5c98Pmif0PTLkXVxN68Zcj4s',
    appId: '1:323532342809:ios:abcdef123456',
    messagingSenderId: '323532342809',
    projectId: 'pocket-organizer-b01f8',
    storageBucket: 'pocket-organizer-b01f8.firebasestorage.app',
    iosBundleId: 'com.ahad.pocketorganizer',
  );
}