name: Refresh FCM Access Token

# This workflow automatically refreshes the FCM access token every hour
# and updates it in MongoDB Atlas

on:
  schedule:
    # Runs every hour at minute 0
    - cron: "0 * * * *"

  # Allow manual trigger for testing
  workflow_dispatch:

jobs:
  refresh-token:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_JSON }}

      - name: Setup Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: Generate FCM Access Token
        id: get-token
        run: |
          # Generate OAuth 2.0 access token
          TOKEN=$(gcloud auth print-access-token)
          echo "token=$TOKEN" >> $GITHUB_OUTPUT
          echo "✅ Token generated: ${TOKEN:0:20}..."

      - name: Update MongoDB Atlas Secret
        env:
          MONGODB_PUBLIC_KEY: ${{ secrets.MONGODB_PUBLIC_KEY }}
          MONGODB_PRIVATE_KEY: ${{ secrets.MONGODB_PRIVATE_KEY }}
          MONGODB_GROUP_ID: ${{ secrets.MONGODB_GROUP_ID }}
          MONGODB_APP_ID: ${{ secrets.MONGODB_APP_ID }}
          FCM_TOKEN: ${{ steps.get-token.outputs.token }}
        run: |
          echo "📤 Updating fcm_access_token in MongoDB Atlas..."

          # MongoDB Atlas App Services API endpoint for updating a value
          # Note: Use /values endpoint, not /secrets
          API_URL="https://realm.mongodb.com/api/admin/v3.0/groups/$MONGODB_GROUP_ID/apps/$MONGODB_APP_ID/values"

          echo "API URL: $API_URL"
          echo "Group ID: $MONGODB_GROUP_ID"
          echo "App ID: $MONGODB_APP_ID"

          # First, get the value ID for fcm_access_token
          echo "Getting existing value ID..."
          GET_RESPONSE=$(curl -s \
            -H "Content-Type: application/json" \
            -u "$MONGODB_PUBLIC_KEY:$MONGODB_PRIVATE_KEY" \
            "$API_URL")

          echo "Response: $GET_RESPONSE"

          # Extract the _id of fcm_access_token value (if it exists)
          VALUE_ID=$(echo "$GET_RESPONSE" | grep -o '"_id":"[^"]*".*"name":"fcm_access_token"' | head -1 | grep -o '"_id":"[^"]*"' | cut -d'"' -f4)

          if [ -n "$VALUE_ID" ]; then
            echo "Found existing value with ID: $VALUE_ID"
            echo "Updating existing value..."
            
            # Update existing value
            UPDATE_RESPONSE=$(curl -s -w "\n%{http_code}" -X PUT \
              -H "Content-Type: application/json" \
              -u "$MONGODB_PUBLIC_KEY:$MONGODB_PRIVATE_KEY" \
              "$API_URL/$VALUE_ID" \
              -d "{\"name\":\"fcm_access_token\",\"value\":\"$FCM_TOKEN\",\"secret\":true}")
            
            HTTP_CODE=$(echo "$UPDATE_RESPONSE" | tail -n1)
            BODY=$(echo "$UPDATE_RESPONSE" | head -n-1)
            
          else
            echo "Value doesn't exist, creating new one..."
            
            # Create new value
            UPDATE_RESPONSE=$(curl -s -w "\n%{http_code}" -X POST \
              -H "Content-Type: application/json" \
              -u "$MONGODB_PUBLIC_KEY:$MONGODB_PRIVATE_KEY" \
              "$API_URL" \
              -d "{\"name\":\"fcm_access_token\",\"value\":\"$FCM_TOKEN\",\"secret\":true}")
            
            HTTP_CODE=$(echo "$UPDATE_RESPONSE" | tail -n1)
            BODY=$(echo "$UPDATE_RESPONSE" | head -n-1)
          fi

          echo "HTTP Code: $HTTP_CODE"
          echo "Response: $BODY"

          if [ "$HTTP_CODE" -eq 200 ] || [ "$HTTP_CODE" -eq 201 ]; then
            echo "✅ Token updated successfully in MongoDB Atlas!"
          else
            echo "❌ Failed to update token. HTTP Code: $HTTP_CODE"
            echo "Response: $BODY"
            exit 1
          fi

      - name: Verify Token Update
        env:
          MONGODB_PUBLIC_KEY: ${{ secrets.MONGODB_PUBLIC_KEY }}
          MONGODB_PRIVATE_KEY: ${{ secrets.MONGODB_PRIVATE_KEY }}
          MONGODB_GROUP_ID: ${{ secrets.MONGODB_GROUP_ID }}
          MONGODB_APP_ID: ${{ secrets.MONGODB_APP_ID }}
        run: |
          echo "🔍 Verifying token was updated..."

          RESPONSE=$(curl -s \
            -H "Content-Type: application/json" \
            -u "$MONGODB_PUBLIC_KEY:$MONGODB_PRIVATE_KEY" \
            "https://realm.mongodb.com/api/admin/v3.0/groups/$MONGODB_GROUP_ID/apps/$MONGODB_APP_ID/secrets")

          if echo "$RESPONSE" | grep -q "fcm_access_token"; then
            echo "✅ Token verified in MongoDB Atlas"
          else
            echo "⚠️ Could not verify token"
          fi

      - name: Notification
        if: always()
        run: |
          if [ "${{ job.status }}" == "success" ]; then
            echo "🎉 FCM Token refresh completed successfully!"
            echo "Next refresh in 1 hour"
          else
            echo "❌ FCM Token refresh failed!"
            echo "Check the logs above for details"
          fi
